# Generated by Django 4.2.7 on 2023-11-30 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('grade_level', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Math_Grade_9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('grade', models.DecimalField(decimal_places=6, max_digits=7)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Math_Grade_10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('grade', models.DecimalField(decimal_places=6, max_digits=7)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='English_Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('grade', models.DecimalField(decimal_places=6, max_digits=7)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades_app.student')),
            ],
        ),
    ]
