# Generated by Django 4.2.7 on 2023-12-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='english_grade',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='math_grade_10',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='math_grade_9',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
