# Generated by Django 4.2.7 on 2023-12-01 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades_app', '0002_alter_english_grade_grade_alter_math_grade_10_grade_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='English_Grade',
            new_name='English_Grade_10',
        ),
        migrations.CreateModel(
            name='English_Grade_9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('grade', models.DecimalField(decimal_places=2, max_digits=6)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades_app.student')),
            ],
        ),
    ]
