# Generated by Django 4.2.7 on 2023-12-01 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades_app', '0003_rename_english_grade_english_grade_10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Math_Grade_12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('grade', models.DecimalField(decimal_places=2, max_digits=6)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Math_Grade_11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('grade', models.DecimalField(decimal_places=2, max_digits=6)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='English_Grade_12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('grade', models.DecimalField(decimal_places=2, max_digits=6)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='English_Grade_11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('grade', models.DecimalField(decimal_places=2, max_digits=6)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades_app.student')),
            ],
        ),
    ]
