# Generated by Django 4.2.7 on 2023-12-04 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades_app', '0004_math_grade_12_math_grade_11_english_grade_12_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='english_grade_10',
            options={'verbose_name_plural': 'English Grade 10'},
        ),
        migrations.AlterModelOptions(
            name='english_grade_11',
            options={'verbose_name_plural': 'English Grade 11'},
        ),
        migrations.AlterModelOptions(
            name='english_grade_12',
            options={'verbose_name_plural': 'English Grade 12'},
        ),
        migrations.AlterModelOptions(
            name='english_grade_9',
            options={'verbose_name_plural': 'English Grade 9'},
        ),
        migrations.AlterModelOptions(
            name='math_grade_10',
            options={'verbose_name_plural': 'Math Grade 10'},
        ),
        migrations.AlterModelOptions(
            name='math_grade_11',
            options={'verbose_name_plural': 'Math Grade 11'},
        ),
        migrations.AlterModelOptions(
            name='math_grade_12',
            options={'verbose_name_plural': 'Math Grade 12'},
        ),
        migrations.AlterModelOptions(
            name='math_grade_9',
            options={'verbose_name_plural': 'Math Grade 9'},
        ),
    ]
