# Generated by Django 5.0 on 2024-01-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades_app', '0006_customgroupdata_customgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customgroup',
            options={'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterField(
            model_name='customgroupdata',
            name='name',
            field=models.CharField(choices=[('High School Math Teachers', 'High School Math Teachers'), ('High School English Teachers', 'High School English Teachers'), ('High School Chemistry Teachers', 'High School Chemistry Teachers'), ('High School Physics Teachers', 'High School Physics Teachers')], max_length=50, unique=True, verbose_name='name'),
        ),
    ]
